### PR TITLE
Add tests to validate notebooks

### PR DESCRIPTION
**Pull request by marpulli**
*Issue #, if available:* #73

*Description of changes:* Tests that notebooks run. Doesn't test the validity of the output.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by apaleyes** [comment]
Can you check what's going on here? Changes from benchmarking PR are now in here too for some reason

**Comment by marpulli** [comment]
It needed a rebase, should  be fixed now.

**Comment by marpulli** [comment]
Notebook tests seem to add around 5 minutes to the build. What do people think about that @apaleyes @javiergonzalezh @mmahsereci ? Mac builds are now 20 minutes and linux are 10 minutes.

**Comment by apaleyes** [comment]
I am fine with that, as long as we find a way to test all notebooks eventually. One obvious idea is to have a separate build run daily (or nightly), that runs full test suite, including all notebooks. Not ideal, but better than nothing.

**Pull request merged**
